### ISSUE TITLE
Is the ntex MSRV really 1.75? Woes trying to build with 1.80

### ISSUE THREAD

**Issue by pdh11** [ntex-rs/ntex#612]
I have an (unpublished) crate with MSRV 1.80 using ntex. I'm sure this used to work!

Now it doesn't compile out-of-the-box. If my Cargo.toml lists ntex version "2", "cargo +1.80 build" fails because (ntex dependency) variadics_please "1.1" has MSRV 1.81.

If I change Cargo.toml to list ntex "2, <2.13.2" to avoid variadics_please, then issue "cargo +1.80 build", I get a slew of errors about, er, errors:
```
error[E0277]: `?` couldn't convert the error to `SendRequestError`
   --> /home/peter/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ntex-2.13.1/src/http/client/h1proto.rs:127:57
    |
127 |                 io.encode(h1::Message::Chunk(Some(result?)), codec)?;
    |                                                         ^ the trait `From<Rc<dyn StdError>>` is not implemented for `SendRequestError`, which is required by `Result<(), SendRequestError>: FromResidual<Result<Infallible, Rc<dyn StdError>>>`
    |
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
    = help: the following other types implement trait `From<T>`:
              <SendRequestError as From<Box<(dyn StdError + 'static)>>>
              <SendRequestError as From<EncodeError>>
              <SendRequestError as From<FreezeRequestError>>
              <SendRequestError as From<InvalidUrl>>
              <SendRequestError as From<OperationError>>
              <SendRequestError as From<PrepForSendingError>>
              <SendRequestError as From<http::client::error::ConnectError>>
              <SendRequestError as From<http::error::DecodeError>>
            and 4 others
    = note: required for `Result<(), SendRequestError>` to implement `FromResidual<Result<Infallible, Rc<dyn StdError>>>`
```

This appears to be because ntex-http 0.1.14 is selected, which changed the error type as compared to ntex-http 0.1.13. I can work around this by explicitly selecting ntex-http "0.1, <0.1.14" in _my_ Cargo.toml, but that shouldn't be necessary as ntex-http isn't a direct dependency of _my_ crate. Was the ntex-http change between 0.1.13 and 0.1.14 in fact semver-breaking?

Even with ntex "2, <2.13.2" and ntex-http "0.1.12, <0.1.14", my build _still_ fails after "cargo +nightly update -Z direct-minimal-versions" -- because ntex-server 2.7.2 is chosen, which relies on a macro "ntex_service::forward_notready" which disappeared between ntex-service 3.3.0 and ntex-service 3.5.0. Isn't that, too, a semver-breaking change in ntex-service?

Again, if I put ntex-service = "3, <3.4" in _my_ Cargo.toml, both the regular and direct-minimal-versions builds succeed with rust 1.80. But again that's awkward, and it makes my crate harder to use as a dependency of crates with _higher_ MSRVs than mine -- which people are entitled to expect will work.

I admit I haven't tried to build ntex with its exact quoted MSRV, 1.75. But quoting an MSRV of 1.75 surely implies that 1.80 should also work.

_edited to clarify that just variadics_please 1.1 is at issue, not all 1.x_

**Comment by fafhrd91** [comment]
i will check but 2.15.1 passes on 1.75

https://github.com/ntex-rs/ntex/actions/runs/16398589316/job/46334679940

**Comment by pdh11** [comment]
Is there a way to see the versions of dependencies used in that CI job? In 2.15.1, commit 73dcc968 of ntex/Cargo.toml says `variadics_please = { workspace = true }`, the workspace Cargo.toml at that revision says `variadics_please = "1.1"`, and variadics_please 1.1.0 requires rustc 1.81 https://crates.io/crates/variadics_please/versions -- so I don't really understand how that build succeeded!

There _was_ an earlier version of variadics_please, 1.0.0, which had MSRV 1.65, so that would work, _except_ that the ntex workspace Cargo.toml explicitly requests variadics_please 1.1.0...

On looking a bit further at those logs, "Run actions-rust-lang/setup-rust-toolchain@v1", which comes _after_ "Install 1.75.0", includes these lines:
```
150 info: override toolchain for '/home/runner/work/ntex/ntex' set to 'stable-x86_64-unknown-linux-gnu'
151 Run echo "rustc-version=$(rustc --version)" >> $GITHUB_OUTPUT
172 rustc 1.88.0 (6b00bc388 2025-06-23)
```

I fear you're not testing what you think you are :( :(

**Comment by fafhrd91** [comment]
something is wrong with gh action. i cannot build with 1.75, ecosystem moved too far.

it is possible to build only on 1.81, variadics_please 1.0 requires 1.81,
you can pin ntex 2.10.0, but you would need to pin ntex-http, ntex-h2 and probably ntex-util as well

**Comment by pdh11** [comment]
So I think there's three issues here:

1. the quoted MSRV wasn't right (documentation error), partly because the Github action was accidentally not testing the intended toolchain

This is almost not-an-issue, because the MSRV-aware resolver picks 2.13.1 for me, the last non-variadics-please version -- which _would_ have worked fine, _except_ for the following two further issues:

2. ntex-http had a breaking change in a patch version, so 0.1.14 should arguably have been 0.2.0 so that ntex-2.13.1 wouldn't attempt to use it;
3. ntex-service had a breaking change in a minor version, so 3.5.0 should arguably have been 4.0.0 so that ntex-2.13.1 wouldn't attempt to use it.

Those are released crate versions of course, and obviously they can't now be changed. But maybe something like cargo-semver-checks could be used to stop similar issues arising in future?

With these pins in my Cargo.toml I'm up and running on Rust 1.80 (I didn't need to pin h2 or util):
```
 # 2.13.2 introduces a dependency on variadics_please with MSRV 1.81
ntex = { version = "2, <2.13.2", features = ["tokio"] }
# Newer ntex-http is incompatible with ntex that old
ntex-http = "0.1.12, <0.1.14"
# Newer ntex-service is incompatible with ntex(-server) that old
ntex-service = "3, <3.5"
```

**Comment by fafhrd91** [comment]
you points are valid. but in general, i dont see much of community or any feedback around ntex framework, so i assume it is mostly use case for my work. i would be more careful with releases if i would have any feedback.
